
import streamlit as st
import pandas as pd
import base64
from io import BytesIO
import folium
from streamlit_folium import st_folium
from risk_matrix import score_vessel_risk
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet

# UI setup
st.title("Enforcement Edge AI: IUU Vessel Risk Reporter")

# File uploader
uploaded_file = st.file_uploader("Upload AIS CSV File", type=["csv"])
if uploaded_file:
    df = pd.read_csv(uploaded_file)
    st.write("Preview of Uploaded Data:")
    st.dataframe(df.head())

    vessel_options = df["Vessel Name"].unique()
    selected_vessels = st.multiselect("Select Vessel(s) to Analyze", vessel_options)

    flag_state = st.selectbox("Select Flag State", options=[
        "Panama", "Liberia", "Marshall Islands", "China", "Taiwan", "Other"
    ])
    false_positive = st.checkbox("Flagged in the past but verified as non-violator?")

    # Show vessel tracks
    if selected_vessels:
        m = folium.Map(location=[0, 180], zoom_start=2)
        for vessel in selected_vessels:
            vessel_df = df[df["Vessel Name"] == vessel]
            coords = list(zip(vessel_df["Latitude"], vessel_df["Longitude"]))
            folium.PolyLine(coords, color="blue", weight=2.5, opacity=1).add_to(m)
            if coords:
                folium.Marker(coords[0], popup=f"{vessel} Start").add_to(m)
                folium.Marker(coords[-1], popup=f"{vessel} End").add_to(m)
        st_folium(m, width=700)

    if st.button("Generate PDF Report(s)"):
        for vessel in selected_vessels:
            vessel_df = df[df["Vessel Name"] == vessel]
            result = score_vessel_risk(vessel_df, flag_state, false_positive)
            buffer = BytesIO()
            doc = SimpleDocTemplate(buffer)
            styles = getSampleStyleSheet()
            story = [
                Paragraph(f"<b>Coast Guard High Seas IUU Vessel Report</b>", styles["Title"]),
                Spacer(1, 12),
                Paragraph(f"<b>Region:</b> Oceania High Seas Pocket", styles["Normal"]),
                Paragraph(f"<b>Generated By:</b> Enforcement Edge AI", styles["Normal"]),
                Paragraph(f"<b>Vessel Name:</b> {vessel}", styles["Normal"]),
                Paragraph(f"<b>MMSI:</b> {result['mmsi']}", styles["Normal"]),
                Paragraph(f"<b>IMO:</b> {result['imo']}", styles["Normal"]),
                Paragraph(f"<b>Flag State:</b> {flag_state}", styles["Normal"]),
                Paragraph(f"<b>Flag Risk Level:</b> {result['flag_risk']}", styles["Normal"]),
                Paragraph(f"<b>Last Known Position:</b> {result['last_position']}", styles["Normal"]),
                Paragraph(f"<b>AIS Dark Activity:</b> {result['ais_dark_hours']} hours offline", styles["Normal"]),
                Paragraph(f"<b>Past Violations:</b> {result['past_violations']}", styles["Normal"]),
                Paragraph(f"<b>Behavior Notes:</b> {result['behavior_notes']}", styles["Normal"]),
                Paragraph(f"<b>Risk Score:</b> {result['risk_score']} / 100", styles["Normal"]),
                Spacer(1, 12),
                Paragraph("<b>Narrative Summary</b>", styles["Heading2"]),
                Paragraph(result["narrative"], styles["Normal"]),
                Spacer(1, 12),
                Paragraph("<b>Action Recommendation</b>", styles["Heading2"]),
                Paragraph(result["recommendation"], styles["Normal"]),
            ]
            doc.build(story)
            st.download_button(
                label=f"Download Report for {vessel}",
                data=buffer.getvalue(),
                file_name=f"{vessel}_iuu_report.pdf",
                mime="application/pdf"
            )
